import test from 'node:test';import assert from 'node:assert/strict';import {createAskUser} from '../core.ts';
function ui(values:(string|undefined)[]){return {hasUI:true,ui:{select:async(_t:string,opts:string[])=>{const value=values.shift();return value==='#first'?opts[0]:value;},input:async()=>values.shift()}};}
test('choices, default Other, context and optional comment',async()=>{const ask=createAskUser();assert.equal((await ask({question:'Pick',options:[{title:'A',description:'Detail'}]},ui(['#first']))).response,'A');assert.equal((await ask({question:'Pick',options:['A'],allowComment:true},ui(['Other (type an answer)','Custom','Note']))).answers[0].comment,'Note');});
test('multi select visibly toggles; explicit Done only',async()=>{const ask=createAskUser();const ctx=ui(['#first','Done (submit selected answers)']);const orig=ctx.ui.select;let count=0;ctx.ui.select=async(t,o)=>{if(count++===1)assert.match(o[0],/^\[x\]/);return orig(t,o)};assert.deepEqual((await ask({question:'Pick',options:['A','B'],allowMultiple:true},ctx)).response,['A']);assert.equal((await ask({question:'Pick',options:['A'],allowMultiple:true},ui(['#first',undefined]))).cancelled,true);});
test('blank and malformed inputs cannot approve',async()=>{const ask=createAskUser();for(const raw of [{question:''},{question:'A',options:[{}]},{question:'A',allowFreeform:false},{question:'A',timeout:0}])assert.equal((await ask(raw,ui([]))).reason,'invalid_arguments');assert.equal((await ask({question:'A'},ui(['  ']))).reason,'blank_input');});
test('headless and aborted request never opens UI',async()=>{const ask=createAskUser();const ctx=ui([]);ctx.hasUI=false;assert.equal((await ask({question:'A'},ctx)).reason,'no_ui');const signal=AbortSignal.abort();assert.equal((await ask({question:'A'},ui([]),signal)).reason,'aborted');});
test('partial batch cancellation retains completed answers',async()=>{const result=await createAskUser()({questions:[{question:'A'},{question:'B'}]},ui(['one',undefined]));assert.equal(result.cancelled,true);assert.equal(result.response,null);assert.equal(result.answers.length,1);assert.equal(result.answers[0].response,'one');});
test('timeout, overlap rejection and recovery',async()=>{const ask=createAskUser();const ctx={hasUI:true,ui:{select:async()=>undefined,input:async()=>new Promise<string>(()=>{})}};const pending=ask({question:'A',timeout:15},ctx);assert.equal((await ask({question:'B'},ui(['ok']))).reason,'busy');assert.equal((await pending).reason,'timeout');assert.equal((await ask({question:'C'},ui(['ok']))).cancelled,false);});
test('abort dismisses native UI signal and releases singleton',async()=>{const ask=createAskUser();const controller=new AbortController();let nativeSignal:AbortSignal|undefined;const ctx={hasUI:true,ui:{select:async()=>undefined,input:async(_t:string,_p:unknown,o:{signal?:AbortSignal})=>{nativeSignal=o.signal;return new Promise<string>(()=>{})}}};const pending=ask({question:'A'},ctx,controller.signal);controller.abort();assert.equal((await pending).reason,'aborted');assert.equal(nativeSignal?.aborted,true);assert.equal((await ask({question:'B'},ui(['ok']))).cancelled,false);});
test('deadline spans batch, cancellation and repeated toggling',async()=>{const ask=createAskUser();let count=0;const ctx={hasUI:true,ui:{select:async()=>undefined,input:async()=>{if(count++===0)return 'ok';return new Promise<string>(()=>{})}}};const result=await ask({questions:[{question:'A'},{question:'B'},{question:'C'}],timeout:13},ctx);assert.equal(result.reason,'timeout');assert.equal(result.response,null);assert.equal(result.answers.length,1);assert.equal((await ask({question:'A',options:['One'],allowMultiple:true},ui(['#first','#first','Done (submit selected answers)']))).reason,'empty_selection');});
test('native remaining timeout and external abort listener cleaned',async()=>{const ask=createAskUser();const controller=new AbortController();let adds=0,removes=0;const add=controller.signal.addEventListener.bind(controller.signal),remove=controller.signal.removeEventListener.bind(controller.signal);controller.signal.addEventListener=((...args:any[])=>{adds++;return add(...args as Parameters<typeof add>);}) as typeof add;controller.signal.removeEventListener=((...args:any[])=>{removes++;return remove(...args as Parameters<typeof remove>);}) as typeof remove;const ctx={hasUI:true,ui:{select:async()=>undefined,input:async(_t:string,_p:unknown,o:{signal?:AbortSignal,timeout?:number})=>{assert(o.signal);assert(o.timeout!>0&&o.timeout!<=1000);return 'answer'}}};assert.equal((await ask({question:'A',timeout:1000},ctx,controller.signal)).cancelled,false);assert.equal(adds,1);assert.equal(removes,1);});
